# Generated by Django 5.0.6 on 2024-07-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('Persian', 'Persian'), ('English', 'English')], default=None, max_length=50, null=True, verbose_name='User default language'),
        ),
    ]
