# Generated by Django 5.0.6 on 2024-06-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUpdateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_update', models.BooleanField(default=False, verbose_name='update status')),
                ('update_msg', models.TextField(default='')),
            ],
        ),
    ]
