# Generated by Django 5.0 on 2024-01-01 12:39

import django.db.models.deletion
import ecommerce.product.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy', models.CharField(max_length=20, verbose_name='proxy(ip:port)')),
                ('api_id', models.CharField(max_length=20, verbose_name='api hash')),
                ('api_hash', models.CharField(max_length=20, verbose_name='api id')),
                ('phone', models.CharField(max_length=20, verbose_name='phone number')),
                ('session_string', models.CharField(max_length=20, verbose_name='session string')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='product name')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='product price')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active product?')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_code', models.CharField(max_length=20, verbose_name='login code')),
                ('price', models.IntegerField(default=0, verbose_name='price')),
                ('track_id', models.CharField(default=ecommerce.product.models.generate_short_uuid, max_length=80, verbose_name='tracking id')),
                ('status', models.CharField(choices=[('انجام شد ✅', 'Down'), ('رد شد ❌', 'Reject'), ('در صف ', 'Waiting')], default='waiting', max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='product.accountsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
