# Generated by Django 5.0 on 2024-01-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disable', 'Disable'), ('limit', 'Limit')], default='', max_length=50, verbose_name='session status'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='country_code',
            field=models.CharField(default='', help_text='like: us, ir, uk and etc..', max_length=50, verbose_name='country code'),
        ),
    ]
