# Generated by Django 5.0 on 2024-01-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_accountsession_status_product_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsession',
            name='password',
            field=models.CharField(default='', max_length=64, verbose_name='related account password'),
        ),
        migrations.AlterField(
            model_name='product',
            name='country_code',
            field=models.CharField(default='', help_text='us, ir, uk and etc..', max_length=50, verbose_name='country code'),
        ),
    ]
