# Generated by Django 5.0 on 2024-01-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_accountsession_password_alter_product_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsession',
            name='password',
            field=models.CharField(default='', max_length=64, verbose_name='account password'),
        ),
        migrations.AlterField(
            model_name='accountsession',
            name='status',
            field=models.CharField(choices=[('فعال ✅', 'Active'), ('غیر فعال ❌', 'Disable'), ('محدود ⚠️', 'Limit'), ('نامشخص 🔘', 'Unknown')], default='unknown', max_length=50, verbose_name='session status'),
        ),
    ]
