# Generated by Django 5.0 on 2024-01-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_accountsession_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsession',
            name='api_hash',
            field=models.CharField(blank=True, max_length=20, verbose_name='api id'),
        ),
        migrations.AlterField(
            model_name='accountsession',
            name='api_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='api hash'),
        ),
        migrations.AlterField(
            model_name='accountsession',
            name='password',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='account password'),
        ),
        migrations.AlterField(
            model_name='accountsession',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='accountsession',
            name='proxy',
            field=models.CharField(blank=True, max_length=50, verbose_name='proxy(ip:port)'),
        ),
        migrations.AlterField(
            model_name='accountsession',
            name='session_string',
            field=models.CharField(max_length=400, verbose_name='session string'),
        ),
        migrations.AlterField(
            model_name='accountsession',
            name='status',
            field=models.CharField(choices=[('فعال ✅', 'Active'), ('غیر فعال ❌', 'Disable'), ('محدود ⚠️', 'Limit'), ('نامشخص 🔘', 'Unknown')], default='نامشخص 🔘', max_length=50, verbose_name='session status'),
        ),
    ]
