# Generated by Django 5.0 on 2024-01-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_accountsession_api_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsession',
            name='api_hash',
            field=models.CharField(blank=True, max_length=50, verbose_name='api id'),
        ),
        migrations.AlterField(
            model_name='accountsession',
            name='status',
            field=models.CharField(choices=[('فعال ✅', 'Active'), ('غیر فعال ❌', 'Disable'), ('محدود ⚠️', 'Limit'), ('نامشخص 🔘', 'Unknown')], default='نامشخص 🔘', max_length=50, verbose_name='session status'),
        ),
    ]
