# Generated by Django 5.0 on 2024-01-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_accountsession_api_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phone_code',
            field=models.CharField(default='', help_text='+98, +1, +964, +234 and etc..', max_length=50, verbose_name='phone code'),
        ),
        migrations.AlterField(
            model_name='accountsession',
            name='status',
            field=models.CharField(choices=[('فعال ✅', 'Active'), ('غیر فعال ❌', 'Disable'), ('محدود ⚠️', 'Limit'), ('نامشخص 🔘', 'Unknown')], default='نامشخص 🔘', max_length=50, verbose_name='session status'),
        ),
    ]
