# Generated by Django 5.0 on 2024-01-08 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_phone_code_alter_accountsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsession',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
    ]
