# Generated by Django 5.0 on 2024-01-22 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_accountsession_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsession',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='product.product'),
        ),
        migrations.AlterField(
            model_name='accountsession',
            name='status',
            field=models.CharField(choices=[('فعال ✅', 'Active'), ('غیر فعال ❌', 'Disable'), ('محدود ⚠️', 'Limit'), ('فروخته شد 💸', 'Purchased'), ('نامشخص 🔘', 'Unknown')], default='نامشخص 🔘', max_length=50, verbose_name='session status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='login_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='login code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('انجام شد ✅', 'Down'), ('رد شد ❌', 'Reject'), ('در صف ', 'Waiting')], default='در صف ', max_length=30),
        ),
    ]
