# Generated by Django 5.0 on 2024-01-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_accountsession_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsession',
            name='status',
            field=models.CharField(choices=[('فعال ✅', 'Active'), ('غیر فعال ❌', 'Disable'), ('محدود ⚠️', 'Limit'), ('فروخته شد 💸', 'Purchased'), ('در انتظار ⏳', 'Wait'), ('نامشخص 🔘', 'Unknown')], default='نامشخص 🔘', max_length=50, verbose_name='session status'),
        ),
    ]
