# Generated by Django 5.0 on 2024-05-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_accountsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsession',
            name='app_version',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='App Version'),
        ),
        migrations.AddField(
            model_name='accountsession',
            name='device_model',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Device Model'),
        ),
        migrations.AddField(
            model_name='accountsession',
            name='system_version',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='System Version'),
        ),
    ]
