# Generated by Django 5.0 on 2024-01-01 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(default=0, verbose_name='amount')),
                ('transaction_id', models.CharField(max_length=70, verbose_name='Transaction Id')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is Paid ?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='payment creation time')),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
